import { Injectable } from '@angular/core';
import { ApiAnalysisResult } from '../models/web-service.model';

@Injectable({
  providedIn: 'root'
})
export class PdfExportService {
  
  async exportToPdf(result: ApiAnalysisResult): Promise<void> {
    // Dynamic import of jsPDF
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF();
    
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const lineHeight = 7;
    let yPosition = margin;

    // Helper function to add text with page break
    const addText = (text: string, fontSize: number = 12, isBold: boolean = false) => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.setFontSize(fontSize);
      doc.setFont('helvetica', isBold ? 'bold' : 'normal');
      doc.text(text, margin, yPosition);
      yPosition += lineHeight;
    };

    // Helper function to add wrapped text
    const addWrappedText = (text: string, fontSize: number = 10) => {
      doc.setFontSize(fontSize);
      const splitText = doc.splitTextToSize(text, pageWidth - 2 * margin);
      for (const line of splitText) {
        if (yPosition > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(line, margin, yPosition);
        yPosition += lineHeight;
      }
    };

    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('API Analysis Report', margin, yPosition);
    yPosition += lineHeight * 2;

    // Service Information
    addText('Service Information', 16, true);
    yPosition += 3;
    addText(`Service: ${result.serviceName}`, 12);
    addText(`URL: ${result.serviceUrl}`, 12);
    addText(`Analyzed: ${new Date(result.analyzedAt).toLocaleString()}`, 12);
    addText(`Overall Score: ${result.overallScore}/100`, 12);
    yPosition += lineHeight;

    // Summary
    addText('Summary', 16, true);
    yPosition += 3;
    addText(`Total Rules Checked: ${result.summary.totalRules}`, 12);
    addText(`Passed: ${result.summary.passedRules}`, 12);
    addText(`Failed: ${result.summary.failedRules}`, 12);
    addText(`Warnings: ${result.summary.warningRules}`, 12);
    yPosition += lineHeight;

    // Violations
    if (result.violations && result.violations.length > 0) {
      addText('Violations and Issues', 16, true);
      yPosition += 3;

      result.violations.forEach((violation, index) => {
        if (yPosition > pageHeight - margin - 50) {
          doc.addPage();
          yPosition = margin;
        }

        addText(`${index + 1}. ${violation.ruleName}`, 12, true);
        addText(`   Category: ${violation.category}`, 10);
        addText(`   Severity: ${violation.severity.toUpperCase()}`, 10);
        
        if (violation.endpoint) {
          addText(`   Endpoint: ${violation.method} ${violation.endpoint}`, 10);
        }
        
        doc.setFontSize(10);
        doc.text('   Description:', margin, yPosition);
        yPosition += lineHeight;
        addWrappedText(`   ${violation.description}`, 10);
        
        doc.text('   Recommendation:', margin, yPosition);
        yPosition += lineHeight;
        addWrappedText(`   ${violation.recommendation}`, 10);
        
        doc.text('   Impact:', margin, yPosition);
        yPosition += lineHeight;
        addWrappedText(`   ${violation.impact}`, 10);
        
        yPosition += lineHeight;
      });
    }

    // Recommendations
    if (result.recommendations && result.recommendations.length > 0) {
      if (yPosition > pageHeight - margin - 50) {
        doc.addPage();
        yPosition = margin;
      }

      addText('Improvement Recommendations', 16, true);
      yPosition += 3;

      result.recommendations.forEach((rec, index) => {
        if (yPosition > pageHeight - margin - 40) {
          doc.addPage();
          yPosition = margin;
        }

        addText(`${index + 1}. ${rec.title}`, 12, true);
        addText(`   Priority: ${rec.priority.toUpperCase()}`, 10);
        addText(`   Category: ${rec.category}`, 10);
        
        doc.text('   Description:', margin, yPosition);
        yPosition += lineHeight;
        addWrappedText(`   ${rec.description}`, 10);
        
        if (rec.actionItems && rec.actionItems.length > 0) {
          doc.text('   Action Items:', margin, yPosition);
          yPosition += lineHeight;
          rec.actionItems.forEach(item => {
            addWrappedText(`   • ${item}`, 10);
          });
        }
        
        yPosition += lineHeight;
      });
    }

    // Footer on last page
    const timestamp = new Date().toISOString();
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Generated by API Inspector on ${timestamp}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );

    // Save the PDF
    const fileName = `api-analysis-${result.serviceName.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`;
    doc.save(fileName);
  }
}

